// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUDvoKq9ayk876ZApGklS9xqJgoY4FqLQ',
    appId: '1:966405629339:web:cd8d323e4d5e095581ed3e',
    messagingSenderId: '966405629339',
    projectId: 'voltrix-3fe38',
    authDomain: 'voltrix-3fe38.firebaseapp.com',
    storageBucket: 'voltrix-3fe38.firebasestorage.app',
    measurementId: 'G-BG4SEHNLVY',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHYXkn2OoBs9eVyk9IiAyD_z2k-abWY-M',
    appId: '1:966405629339:ios:cba53f0afa172a7681ed3e',
    messagingSenderId: '966405629339',
    projectId: 'voltrix-3fe38',
    storageBucket: 'voltrix-3fe38.firebasestorage.app',
    iosBundleId: 'com.example.voltrix',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHYXkn2OoBs9eVyk9IiAyD_z2k-abWY-M',
    appId: '1:966405629339:ios:cba53f0afa172a7681ed3e',
    messagingSenderId: '966405629339',
    projectId: 'voltrix-3fe38',
    storageBucket: 'voltrix-3fe38.firebasestorage.app',
    iosBundleId: 'com.example.voltrix',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHkyZ6YmN71mV5aHUiZ59P0o18POB8LzA',
    appId: '1:966405629339:android:e524cb8fcfe4bb6281ed3e',
    messagingSenderId: '966405629339',
    projectId: 'voltrix-3fe38',
    storageBucket: 'voltrix-3fe38.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUDvoKq9ayk876ZApGklS9xqJgoY4FqLQ',
    appId: '1:966405629339:web:cc88b3db08c26b4681ed3e',
    messagingSenderId: '966405629339',
    projectId: 'voltrix-3fe38',
    authDomain: 'voltrix-3fe38.firebaseapp.com',
    storageBucket: 'voltrix-3fe38.firebasestorage.app',
    measurementId: 'G-5H2WSMHRJ9',
  );

}